---

- name: bird-lg-proxy - Create bird-lg-go directory
  file:
    path: /opt/towalink/bird-lg-go
    state: directory
    mode: 0755

- name: bird-lg-proxy - Download bird-lg-go-proxy (amd64 [x86_64] architecture)
  get_url:
    url: https://install.towalink.net/bird-lg-go/bird-lg-proxy_amd64
    dest: /opt/towalink/bird-lg-go/bird-lg-proxy
    mode: 0740
  when: (ansible_architecture == 'x86_64')

- name: bird-lg-proxy - Download bird-lg-go-proxy (arm architecture)
  get_url:
    url: https://install.towalink.net/bird-lg-go/bird-lg-proxy_arm
    dest: /opt/towalink/bird-lg-go/bird-lg-proxy
    mode: 0740
  when: (ansible_architecture[0:3] == 'arm')

- name: bird-lg-proxy - Copying init script (Alpine)
  copy:
    src: files/etc_initd/towalink_bird-lg-proxy
    dest: /etc/init.d/towalink_bird-lg-proxy
    mode: 0755
  when: ansible_facts['os_family'] == 'Alpine'

- name: bird-lg-proxy - Copying init script (Debian)
  copy:
    src: files/etc_systemd_system/towalink_bird-lg-proxy.service
    dest: /etc/systemd/system/towalink_bird-lg-proxy.service
    mode: 0755
  when: ansible_facts['os_family'] == 'Debian'

- name: bird-lg-proxy - Enable bird-lg-proxy service
  service:
    name: towalink_bird-lg-proxy
    state: started
    enabled: yes
